apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pxl-api
spec:
  selector:
    matchLabels:
      app: pxl-api
  replicas: 1
  template:
    metadata:
      labels:
        app: pxl-api
    spec:
      imagePullSecrets:
        - name: ${secret}
      containers:
      - name: pxl-api
        image: phenry20/pixelynx:api-${version}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: ${environment}
        readinessProbe:
            failureThreshold: 3
            httpGet:
                path: /healthz
                port: 5000
                scheme: HTTP
        ports:
        - containerPort: 5000
          name: app-port
          protocol: TCP

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy",
                  "-instances=${project}:${database}=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: service-account-token