

variables: 
  REGISTRY: registry.gitlab.com
  CONTAINER_RELEASE_IMAGE: $REGISTRY/cosmic9studios/assetstore/api

stages:
  - build
  - deploy

build:
  image: docker:git
  services:
  - docker:dind
  stage: build
  before_script:
    - apk add --update nodejs nodejs-npm
    - npm install -g semantic-release@15 @semantic-release/exec @semantic-release/commit-analyzer @semantic-release/gitlab
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE:latest .
    - npx semantic-release -b $CI_COMMIT_REF_NAME -r https://gitlab.com/cosmic9studios/assetstore/api.git
  except: 
    - tags
  only: 
    - master

deploy: 
  image: 
    name: pulumi/pulumi
    entrypoint: [""]
  stage: deploy
  environment: production
  before_script: 
    - apt-get install -y nodejs
  script:
    - cd infra
    - npm install yarn
    - yarn install
    - npx tsc
    - pulumi stack select dev
    - pulumi config set version $CI_COMMIT_TAG
    - pulumi config set gitlabUser gitlab-ci-token
    - pulumi config set gitlabPass $CI_BUILD_TOKEN
    - pulumi up -y
  only: 
    - tags