image: docker:git
services:
  - docker:dind

variables: 
  REGISTRY: registry.gitlab.com
  CONTAINER_RELEASE_IMAGE: $REGISTRY/cosmic9studios/assetstore/web:api

stages:
  - build
  - deploy

build:
  
  stage: build
  script:
    - cd api
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

deploy: 
  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  stage: deploy
  environment: production
  script:
    - dotnet tool install Octopus.DotNet.Cli --global
    - octo create-release --project AssetStore --server https://cosmic9studios.octopus.app/ --apiKey $OCTO_KEY

#deploy:
#  stage: deploy
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#    - docker push $CONTAINER_RELEASE_IMAGE
#  only:
#    - master
