apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pxl-web-deployment
spec:
  selector:
    matchLabels:
      app: pxl-web
  replicas: 1
  template:
    metadata:
      labels:
        app: pxl-web
    spec:
      containers:
      - name: pxl-web
        image: phenry20/pixelynx:web-${version}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: ${environment}
        livenessProbe:
            failureThreshold: 3
            httpGet:
                path: /healthz
                port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
        readinessProbe:
            failureThreshold: 3
            httpGet:
                path: /healthz
                port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
        ports:
        - containerPort: 5000
      imagePullSecrets:
        - name: regcred