apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: assetstore-deployment
spec:
  selector:
    matchLabels:
      app: assetstore
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: assetstore
    spec:
      containers:
      - name: api
        image: registry.gitlab.com/cosmic9studios/assetstore/web:1.0-api
        imagePullPolicy: "Always"
        ports:
          - containerPort: 80