apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: assetstore-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - cosmic9studios.com
    - secretName: letsencrypt-prod
  rules:
  - host: cosmic9studios.com
    http:
      paths:
      - path: /
        backend:
          serviceName: assetstore-svc
          servicePort: 80
---

apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: phenry@cosmic9studios.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    http01:
        ingress: assetstore-ingress

apiVersion: v1
kind: Service
metadata:
  name: assetstore-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
  selector:
    app: assetstore
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: assetstore-deployment
spec:
  selector:
    matchLabels:
      app: assetstore
  replicas: 1
  template:
    metadata:
      labels:
        app: assetstore
    spec:
      containers:
      - name: api
        image: registry.gitlab.com/cosmic9studios/assetstore/web:1.0-api
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: gitlab-auth
---

