apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: assetstore-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: assetstore-svc
          servicePort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: assetstore-svc
spec:
  ports:
    - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: assetstore
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: assetstore-deployment
spec:
  selector:
    matchLabels:
      app: assetstore
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: assetstore
    spec:
      containers:
        - name: api
        image: https://registry.gitlab.com/cosmic9studios/assetstore/web:1.0-api
        imagePullPolicy: "Always"
        ports:
          - containerPort: 5000
      imagePullSecrets:
        - name: gitlab-auth
---

