name: build
on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  build_and_push:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1

    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Test
      run: dotnet test

    - name: Build
      env:
        CONTAINER_RELEASE_IMAGE: docker.pkg.github.com/phenry20/pixelynx-api/pixelynx-api
      run: |
        docker build -t $CONTAINER_RELEASE_IMAGE:latest .
    
    - name: Use Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    
    - name: Push Docker Image
      if: github.ref == 'refs/heads/master'
      env:
        CONTAINER_RELEASE_IMAGE: docker.pkg.github.com/phenry20/pixelynx-api/pixelynx-api
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
        npm install -g semantic-release@15.13.24 @semantic-release/exec @semantic-release/commit-analyzer @semantic-release/github
        echo ${{ secrets.CI_TOKEN }} | docker login docker.pkg.github.com --username "phenry20" --password-stdin
        npx semantic-release -b master