name: build
on:
    push:
        branches:
            - "*"
            - "*/*"

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Test
              if: github.ref != 'refs/heads/master'
              run: |
                dotnet test

            - name: Build
              if: github.ref != 'refs/heads/master'
              env:
                  CONTAINER_RELEASE_IMAGE: phenry20/pixelynx
              run: |
                  docker build -t $CONTAINER_RELEASE_IMAGE:latest .

            - name: Semantic Release
              if: github.ref == 'refs/heads/master'
              uses: codfish/semantic-release-action@v1
              id: semantic
              env:
                  GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
