name: 'Deploy'
on: ['deployment']

jobs:
  deploy_staging:
    if: contains(github.ref, 'refs/tags') && github.event.deployment.environment == 'staging'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volcano-coffee-company/setup-terraform@v1
      with:
        version: '~0.12'

    - name: Add GPG
      run: apt-get install -y gnupg2

    - name: Deploy Production
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: "./pixelynx.json"
      run: |
        cd deployment/staging
        ../deploy.sh ${{ secrets.ACCOUNT_JSON_CREDENTIALS }} Staging
  
  deploy_production:
    if: contains(github.ref, 'refs/tags') && github.event.deployment.environment == 'production'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volcano-coffee-company/setup-terraform@v1
      with:
        version: '~0.12'

    - name: Add GPG
      run: apt-get install -y gnupg2

    - name: Deploy Production
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: "./pixelynx.json"
      run: |
        cd deployment/production
        ../deploy.sh ${{ secrets.ACCOUNT_JSON_CREDENTIALS }} Production