name: 'Deploy'
on: ['deployment']

jobs:
  deploy_staging:
    if: contains(github.ref, 'refs/tags') && github.event.deployment.environment == 'staging'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volcano-coffee-company/setup-terraform@v1
      with:
        version: '0.12.21'

    - name: Add GPG
      run: | 
        sudo apt-get update
        sudo apt-get install -y gnupg2

    - name: Deploy Staging
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: "./pixelynx.json"
      run: |
        cd _deployment
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ACCOUNT_JSON_CREDENTIALS }}" --output $GOOGLE_APPLICATION_CREDENTIALS ./staging/pixelynx-staging.json.gpg
        ./deploy.sh Staging
  
  deploy_production:
    if: contains(github.ref, 'refs/tags') && github.event.deployment.environment == 'production'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: volcano-coffee-company/setup-terraform@v1
      with:
        version: '0.12.21'

    - name: Add GPG
      run: | 
        sudo apt-get update
        sudo apt-get install -y gnupg2

    - name: Deploy Production
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: "./pixelynx.json"
      run: |
        cd _deployment
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ACCOUNT_JSON_CREDENTIALS }}" --output $GOOGLE_APPLICATION_CREDENTIALS ./production/pixelynx.json.gpg
        ./deploy.sh Production