name: 'Deploy'
on: ['deployment']

jobs:
  deploy_staging:
    if: contains(github.ref, 'refs/tags') && github.event.deployment.environment == 'staging'
    runs-on: ubuntu-latest
    container: cytopia/terragrunt
    steps:
    - uses: actions/checkout@v1

    - name: Add GPG
      run: apk add gnupg

    - name: Deploy
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: "./pixelynx.json"
      run: deployment/staging/deploy.sh ${{ secrets.ACCOUNT_JSON_CREDENTIALS }}

    - name: Update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        env: staging
        env_url: https://staging.pixelynx.com/api
        status: ${{ job.status }}
        deployment_id: ${{ github.event.deployment.id }}
  
  deploy_production:
    if: contains(github.ref, 'refs/tags') && github.event.deployment.environment == 'production'
    runs-on: ubuntu-latest
    container: cytopia/terragrunt
    steps:
    - uses: actions/checkout@v1

    - name: Add GPG
      run: apk add gnupg

    - name: Deploy
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: "./pixelynx.json"
      run: deployment/production/deploy.sh ${{ secrets.ACCOUNT_JSON_CREDENTIALS }}

    - name: Update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        env: staging
        env_url: https://pixelynx.com/api
        status: ${{ job.status }}
        deployment_id: ${{ github.event.deployment.id }}