name: Tag Deploy
on:
  push:
    tags:
    - '*'

jobs:
  deploy_staging_tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Push Docker Image
      uses: RafikFarhad/push-to-gcr-github-action@v3
      with:
        gcloud_service_key: ${{ secrets.GCP_SERVICE_KEY_STAGING }}
        registry: gcr.io
        project_id: pixelynx-staging
        image_name: pixelynx-api
        image_tag: latest,${{ steps.get_version.outputs.VERSION }}
    
    - name: Deploy service to Cloud Run
      if: success()
      uses: stefda/action-cloud-run@v1.0
      with:
        image: gcr.io/pixelynx-staging/pixelynx-api:${{ steps.get_version.outputs.VERSION }}
        service: pixelynx-api
        project: pixelynx-staging
        region: us-central1
        env: ./staging.env
        service key: ${{ secrets.GCP_SERVICE_KEY_STAGING }}
    

  
        