name: Release
on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: volcano-coffee-company/setup-terraform@v1
      with:
        version: '~0.12'

    - name: Add GPG
      run: sudo apt-get install -y gnupg2

    - name: Release
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: "./pixelynx.json"
      run: |
        cd deployment/staging
        ../deploy.sh ${{ secrets.ACCOUNT_JSON_CREDENTIALS }} Staging